name: Build and Deploy Slides

on:
  push:
    branches: [main]
    paths: [slides]

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container:
      image: docker://pandoc/core:latest
      options: --entrypoint=sh
    steps:
      - name: Install Git
        run: |
          apk add --no-cache git
      
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Create output directory
        run: |
          mkdir output

      - name: Generate
        run: |
          git diff-tree --no-commit-id --name-only -r HEAD~ slides | xargs -I{} sh -c 'pandoc {} -o output/$(basename {} .md).html --to revealjs --standalone -V revealjs-url=https://unpkg.com/reveal.js@^4' \;

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: gh-pages
          folder: 'output'

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: slides
          path: output
