name: Build and Deploy Slides

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Create output directory
        run: |
          mkdir output

      - name: Generate
        uses: docker://pandoc/core:latest
        with:
          args: >-
            --to revealjs
            --standalone
            --output output/index.html
            slides.md
            -V revealjs-url=https://unpkg.com/reveal.js@^4

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: 'output'

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: slides
          path: output
