name: Build and Deploy Slides

on:
  push:
    branches: [main]
    paths: [slides]

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container:
      image: docker://pandoc/core:latest
      options: --entrypoint=sh
    steps:
      - name: Install Git
        run: |
          apk add --no-cache git
      
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create output directory
        run: |
          mkdir output

      - name: Generate
        run: |
          find slides -iname "*.md" -type f -exec /bin/sh -c 'pandoc ${0} -o output/$(basename ${0} .md).html --to revealjs --standalone -V revealjs-url=https://unpkg.com/reveal.js@^4' {} \;

      - name: Install rsync
        run: |
          apk add --no-cache rsync

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: 'output'

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: slides
          path: output
